
# PyTorch Broadcasting: A Practical Mini-Notebook

**Goal:** Build intuition for PyTorch broadcasting—what it is, when it works, when it fails—and practice with short exercises.

**You will learn to:**
- Read and reason about tensor shapes
- Apply broadcasting rules correctly
- Use `unsqueeze`and `None` indexing
- Spot & fix common broadcasting bugs (wrong axes, shape mismatch)


## Setup

In [26]:
import torch
torch.__version__, torch.cuda.is_available()


('2.2.2+cu121', False)


## Broadcasting in a Nutshell

**Equal Number of Dimensions:** <mark>If the tensors have a different number of dimensions, PyTorch implicitly adds leading (left-side) dimensions of size 1 to the tensor with fewer dimensions until both tensors have the same number of dimensions.

**Compatibility rule (right-aligned):** Compare shapes from **right to left**. For each axis pair:
- If they are **equal**, they're compatible on that axis.
- If **one is 1**, it's broadcast (virtually repeated) to match the other.
- Otherwise, shapes are **incompatible** → runtime error.

**Key tools & idioms**
- `x.unsqueeze(dim)` / `x[:, None]` to create size-1 axes

**Important:** Broadcasting is **virtual**—no memory copies


## Quick Demos

In [29]:
#squeeze and unsqueeze
x=torch.ones(2)
print(f'x.shape: {x.shape}, x = {x}')  #[2]

x=torch.unsqueeze(x,1)  
print(f'x.shape: {x.shape}, x = {x}')  #[2,1]

x=torch.squeeze(x,1)  #gets rid of the dimension if the dimension is 1, nothing otherwise
# x=x.squeeze(1)      #same thing

print(f'x.shape: {x.shape}, x = {x}')  #[2]


x.shape: torch.Size([2]), x = tensor([1., 1.])
x.shape: torch.Size([2, 1]), x = tensor([[1.],
        [1.]])
x.shape: torch.Size([2]), x = tensor([1., 1.])


In [30]:

# Demo 1:
a = torch.randn(1, 6)
print(f"a: {a}, a.shape={a.shape}")

c = torch.randn(5, 1)
print(f"c: {c}, c.shape={c.shape}")

out = a + c  # -> [5, 6]
print("out:", out)
print("out.shape:", out.shape)


a: tensor([[-0.8920, -1.5091,  0.3704,  1.4565,  0.9398,  0.7748]]), a.shape=torch.Size([1, 6])
c: tensor([[ 0.1919],
        [ 1.2638],
        [-1.2904],
        [-0.7911],
        [-0.0209]]), c.shape=torch.Size([5, 1])
out: tensor([[-0.7001, -1.3172,  0.5623,  1.6484,  1.1317,  0.9667],
        [ 0.3718, -0.2453,  1.6342,  2.7203,  2.2036,  2.0386],
        [-2.1824, -2.7995, -0.9200,  0.1661, -0.3506, -0.5156],
        [-1.6831, -2.3002, -0.4207,  0.6654,  0.1487, -0.0163],
        [-0.9129, -1.5300,  0.3495,  1.4356,  0.9189,  0.7540]])
out.shape: torch.Size([5, 6])


In [21]:

# Demo 2: Add [B, D] and [D] -> [B, D]
B, D = 4, 3
x = torch.arange(B*D, dtype=torch.float32).reshape(B, D)
print("x.shape:", x.shape)
print(x)
b = torch.tensor([10.0, 20.0, 30.0])   # shape [D]
print("b.shape:", b.shape)
print(b)
y = x + b
print("x.shape:", x.shape, "| b.shape:", b.shape, "| y.shape:", y.shape)
print(y)


x.shape: torch.Size([4, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
b.shape: torch.Size([3])
tensor([10., 20., 30.])
x.shape: torch.Size([4, 3]) | b.shape: torch.Size([3]) | y.shape: torch.Size([4, 3])
tensor([[10., 21., 32.],
        [13., 24., 35.],
        [16., 27., 38.],
        [19., 30., 41.]])


In [35]:
#start here 9/9/26
# Demo 3: Add [B, D] and [B, 1] -> [B, D]
x = torch.arange(12.0).reshape(4, 3)
print(f' x.shape={x.shape}')
row_bias = torch.tensor([[100.0],[200.0],[300.0],[400.0]])
print("row_bias.shape:", row_bias.shape)

y = x + row_bias
print("x.shape:", x.shape, "| row_bias.shape:", row_bias.shape, "| y.shape:", y.shape)
print(y)


 x.shape=torch.Size([4, 3])
row_bias.shape: torch.Size([4, 1])
x.shape: torch.Size([4, 3]) | row_bias.shape: torch.Size([4, 1]) | y.shape: torch.Size([4, 3])
tensor([[100., 101., 102.],
        [203., 204., 205.],
        [306., 307., 308.],
        [409., 410., 411.]])


In [36]:

# Demo 4: Using unsqueeze to align axes
x = torch.arange(12.0).reshape(4, 3)         # [4, 3]
print("x.shape:", x.shape)
col = torch.tensor([1.0, 2.0, 3.0, 4.0])     # [4]
print("col.shape:", col.shape)
print("col:", col)
y_bad = None
try:
    y_bad = x + col          # incompatible: [4,3] + [4]
except Exception as e:
    print("As expected, this fails: it adds a 1 to the left of col making it [1,4] which is incompatible with [4,3]\n", e)

# Fix via unsqueeze at axis 1 (-> [4,1])
y_ok = x + col.unsqueeze(1)  #->[4,1]
print("Fixed:", y_ok.shape)
print(y_ok)


x.shape: torch.Size([4, 3])
col.shape: torch.Size([4])
col: tensor([1., 2., 3., 4.])
As expected, this fails: it adds a 1 to the left of col making it [1,4] which is incompatible with [4,3]
 The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1
Fixed: torch.Size([4, 3])
tensor([[ 1.,  2.,  3.],
        [ 5.,  6.,  7.],
        [ 9., 10., 11.],
        [13., 14., 15.]])



### Example: NCHW Images (Batch, N Channels, Height, Width)

![](./batch_image_tensors.png)<br><br>


Common pattern: apply per-channel bias/scale to an image batch `x` with shape `[B, N, H, W]`.


In [37]:

B, N, H, W = 2, 3, 4, 5
x = torch.randn(B, N, H, W)
scale_c = torch.tensor([0.5, 2.0, 1.5])     
bias_c  = torch.tensor([0.1, -0.2, 0.0])    
print("x:", x.shape, "scale_c:", scale_c.shape, "bias_c:", bias_c.shape)

# Broadcast to [B, N, H, W] by inserting singleton axes: [1, C, 1, 1]
scale_c_s=scale_c[None, :, None, None]
bias_c_s=bias_c[None, :, None, None]
print("scale_c_s:", scale_c_s.shape, "bias_c_s:", bias_c_s.shape)
print(scale_c_s)

y = x * scale_c_s + bias_c_s
print("x:", x.shape, "y:", y.shape)


x: torch.Size([2, 3, 4, 5]) scale_c: torch.Size([3]) bias_c: torch.Size([3])
scale_c_s: torch.Size([1, 3, 1, 1]) bias_c_s: torch.Size([1, 3, 1, 1])
tensor([[[[0.5000]],

         [[2.0000]],

         [[1.5000]]]])
x: torch.Size([2, 3, 4, 5]) y: torch.Size([2, 3, 4, 5])



## Common Pitfalls & Fixes

1) **Wrong axis alignment:** Added dimension on wrong axis so operation fails.
- **Fix:** `unsqueeze` (or `None`) in the correct axis.

2) **Incompatible shapes:** Read from right to left; insert 1-sized axes where needed.


## Exercise


### Row/Column Normalization

Given `X` with shape `[B, D]`:
1. Compute **column-wise** mean and std → shapes `[D]`.
2. Normalize `X` to `Z = (X - mean) / std` using **broadcasting** (no loops).

**Starter code (fill the TODOs):**


In [25]:

torch.manual_seed(0)
B, D = 5, 4
X = torch.randn(B, D)
# 1) column-wise mean/std
column_mean = X.mean(dim=0)              # [D] dim=0 means calculate along rows
column_std  = X.std(dim=0)              # [D]
print(f'column_mean={column_mean}, column_mean.shape={column_mean.shape}')
print(f'Manual check of 0th column mean X[:,0].mean()={X[:,0].mean()}')
print(f'column_std={column_std}, column_std.shape={column_std.shape}\n')

# 2) Column-wise normalization: Z_feat = (X - column_mean) / column_std
# TODO: broadcast subtraction/division correctly
# Z_feat = ...

# 3) Row-wise (per sample) normalization: Z_row
row_mean = X.mean(dim=1, keepdim=True) # [B, 1]
row_std  = X.std(dim=1, keepdim=True)  # [B, 1]
# # TODO: compute Z_row
# Z_row = ...

# Quick checks (should be ~0 and ~1; small numeric devs OK)
# print("Column-wise mean ~0:", Z_feat.mean(dim=0))
# print("Column-wise std  ~1:", Z_feat.std(dim=0))
# print("Row-wise mean    ~0:", Z_row.mean(dim=1))
# print("Row-wise std     ~1:", Z_row.std(dim=1))


column_mean=tensor([ 0.4525, -0.0040,  0.7606,  0.1790]), column_mean.shape=torch.Size([4])
Manual check of 0th column mean X[:,0].mean()=0.4524577558040619
column_std=tensor([0.9514, 1.4029, 1.0352, 1.0304]), column_std.shape=torch.Size([4])



---
## Solution (reveal after attempting)

### Solution:

In [ ]:

torch.manual_seed(0)
B, D = 5, 4
X = torch.randn(B, D)
# 1) column-wise mean/std
column_mean = X.mean(dim=0)              # [D]
column_std  = X.std(dim=0)              # [D]
print(f'column_mean={column_mean}, column_mean.shape={column_mean.shape}')
print(f'Manual check of 0th column mean X[:,0].mean()={X[:,0].mean()}')
print(f'column_std={column_std}, column_std.shape={column_std.shape}\n')


# 2) Column-wise normalization: Z_feat = (X - column_mean) / column_std
# TODO: broadcast subtraction/division correctly
Z_feat = (X - column_mean[None, :]) / column_std[None, :]
# or
# Z_feat = (X - column_mean.unsqueeze(0)) / column_std.unsqueeze(0)

# 3) Row-wise (per sample) normalization: Z_row
row_mean = X.mean(dim=1, keepdim=True)       # [B, 1]
row_std  = X.std(dim=1, keepdim=True)  # [B, 1]
# # TODO: compute Z_row
Z_row = (X - row_mean) / row_std

# Quick checks (should be ~0 and ~1; small numeric devs OK)
print("Column-wise mean ~0:", Z_feat.mean(dim=0))
print("Column-wise std  ~1:", Z_feat.std(dim=0))
print("Row-wise mean    ~0:", Z_row.mean(dim=1))
print("Row-wise std     ~1:", Z_row.std(dim=1))
